runtime: nodejs
env: flex

env_variables:
  PUBSUB_TOPIC: projects/charged-sled-325502/topics/so1
  # This token is used to verify that requests originate from your
  # application. It can be any sufficiently random string.
  